In [1]:
from utils import pr
from utils import measure_time
import numpy as np
import pandas as pd

In [2]:
import pandas as pd

df = pd.DataFrame({
    "user_id": ["001", "002", "003", "004"],
    "age": ["25", "unknown", "40", None],
    "signup_date": ["2023-01-10", "2023-01-12", None, "2023-01-20"],
    "is_premium": ["True", "False", "False", "True"],
    "monthly_spend": ["100.5", "0", "N/A", "250.0"]
})

In [3]:
pr(df)
pr(df.dtypes)

+++++++++++++++++++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id      age signup_date is_premium monthly_spend
0     001       25  2023-01-10       True         100.5
1     002  unknown  2023-01-12      False             0
2     003       40         NaN      False           N/A
3     004      NaN  2023-01-20       True         250.0

-----

+++++++++++++++++++++++++++++++++++
<class 'pandas.Series'>

user_id          str
age              str
signup_date      str
is_premium       str
monthly_spend    str
dtype: object

-----

In [4]:
df['signup_date'] = pd.to_datetime(df['signup_date'])
pr(df)
pr(df.dtypes)

+++++++++++++++++++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id      age signup_date is_premium monthly_spend
0     001       25  2023-01-10       True         100.5
1     002  unknown  2023-01-12      False             0
2     003       40         NaT      False           N/A
3     004      NaN  2023-01-20       True         250.0

-----

+++++++++++++++++++++++++++++++++++
<class 'pandas.Series'>

user_id                     str
age                         str
signup_date      datetime64[us]
is_premium                  str
monthly_spend               str
dtype: object

-----

In [5]:
df['monthly_spend'] = pd.to_numeric(df['monthly_spend'] , errors='coerce')
df['age'] = pd.to_numeric(df['age'] , errors='coerce')
pr(df)
pr(df.dtypes)

+++++++++++++++++++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id   age signup_date is_premium  monthly_spend
0     001  25.0  2023-01-10       True          100.5
1     002   NaN  2023-01-12      False            0.0
2     003  40.0         NaT      False            NaN
3     004   NaN  2023-01-20       True          250.0

-----

+++++++++++++++++++++++++++++++++++
<class 'pandas.Series'>

user_id                     str
age                     float64
signup_date      datetime64[us]
is_premium                  str
monthly_spend           float64
dtype: object

-----

In [6]:
df['is_premium'] = df['is_premium'].map({'True':True , 'False':False})
pr(df)
pr(df.dtypes)

+++++++++++++++++++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id   age signup_date  is_premium  monthly_spend
0     001  25.0  2023-01-10        True          100.5
1     002   NaN  2023-01-12       False            0.0
2     003  40.0         NaT       False            NaN
3     004   NaN  2023-01-20        True          250.0

-----

+++++++++++++++++++++++++++++++++++
<class 'pandas.Series'>

user_id                     str
age                     float64
signup_date      datetime64[us]
is_premium                 bool
monthly_spend           float64
dtype: object

-----