In [1]:
from utils import pr
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    "user_id": ["001", "002", "003", "004", "005"],
    "age": [25, np.nan, 40, np.nan, 30],
    "income": [5000, 0, np.nan, 7000, np.nan],
    "last_login_days_ago": [5, np.nan, 30, 0, np.nan],
    "churned": [False, True, False, False, True]
})
pr(df , 'df')
pr(df.isna() , 'df.isna()')
pr(df.isna().sum() , 'df.isna().sum()')
pr(df.copy().fillna(0) , "Don't do this it's dangerous")

+++++++++++++++++ df ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id   age  income  last_login_days_ago  churned
0     001  25.0  5000.0                  5.0    False
1     002   NaN     0.0                  NaN     True
2     003  40.0     NaN                 30.0    False
3     004   NaN  7000.0                  0.0    False
4     005  30.0     NaN                  NaN     True

-----

+++++++++++++++++ df.isna() ++++++++++++++++++
<class 'pandas.DataFrame'>

   user_id    age  income  last_login_days_ago  churned
0    False  False   False                False    False
1    False   True   False                 True    False
2    False  False    True                False    False
3    False   True   False                False    False
4    False  False    True                 True    False

-----

+++++++++++++++++ df.isna().sum() ++++++++++++++++++
<class 'pandas.Series'>

user_id                0
age                    2
income                 2
last_login_days_ago    2
churned                0
dtype: int64

-----

+++++++++++++++++ Don't do this it's dangerous ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id   age  income  last_login_days_ago  churned
0     001  25.0  5000.0                  5.0    False
1     002   0.0     0.0                  0.0     True
2     003  40.0     0.0                 30.0    False
3     004   0.0  7000.0                  0.0    False
4     005  30.0     0.0                  0.0     True

-----

In [3]:
pr(df , 'df')
df['missing_income'] = df['income'].isna()
pr(df , 'df')

+++++++++++++++++ df ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id   age  income  last_login_days_ago  churned
0     001  25.0  5000.0                  5.0    False
1     002   NaN     0.0                  NaN     True
2     003  40.0     NaN                 30.0    False
3     004   NaN  7000.0                  0.0    False
4     005  30.0     NaN                  NaN     True

-----

+++++++++++++++++ df ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id   age  income  last_login_days_ago  churned  missing_income
0     001  25.0  5000.0                  5.0    False           False
1     002   NaN     0.0                  NaN     True           False
2     003  40.0     NaN                 30.0    False            True
3     004   NaN  7000.0                  0.0    False           False
4     005  30.0     NaN                  NaN     True            True

-----