In [1]:
from utils import pr
import numpy as np
import pandas as pd

In [2]:
# Main table: users
users = pd.DataFrame(
    {
        "user_id": ["U1", "U2", "U3", "U4"],
        "signup_date": pd.to_datetime(
            ["2023-01-01", "2023-01-05", "2023-01-10", "2023-01-15"]
        ),
        "churned": [False, True, False, True],
    }
)
#  Secondary table: transactions
transactions = pd.DataFrame(
    {
        "user_id": ["U1", "U1", "U2", "U3", "U3", "U3"],
        "transaction_date": pd.to_datetime(
            [
                "2023-01-03",
                "2023-02-10",
                "2023-01-06",
                "2023-01-12",
                "2023-01-20",
                "2023-02-05",
            ]
        ),
        "amount": [100, 500, 50, 200, 300, 400],
    }
)
pr(users, 'users')
pr(transactions , 'transactions')

+++++++++++++++++ users ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id signup_date  churned
0      U1  2023-01-01    False
1      U2  2023-01-05     True
2      U3  2023-01-10    False
3      U4  2023-01-15     True

-----

+++++++++++++++++ transactions ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id transaction_date  amount
0      U1       2023-01-03     100
1      U1       2023-02-10     500
2      U2       2023-01-06      50
3      U3       2023-01-12     200
4      U3       2023-01-20     300
5      U3       2023-02-05     400

-----

In [4]:
pr(users.merge(transactions, on="user_id", how="inner"), "inner")
pr(users.merge(transactions, on="user_id", how="outer"), "outer")
pr(users.merge(transactions, on="user_id", how="left"), "left")
pr(users.merge(transactions, on="user_id", how="right"), "right")

+++++++++++++++++ inner ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id signup_date  churned transaction_date  amount
0      U1  2023-01-01    False       2023-01-03     100
1      U1  2023-01-01    False       2023-02-10     500
2      U2  2023-01-05     True       2023-01-06      50
3      U3  2023-01-10    False       2023-01-12     200
4      U3  2023-01-10    False       2023-01-20     300
5      U3  2023-01-10    False       2023-02-05     400

-----

+++++++++++++++++ outer ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id signup_date  churned transaction_date  amount
0      U1  2023-01-01    False       2023-01-03   100.0
1      U1  2023-01-01    False       2023-02-10   500.0
2      U2  2023-01-05     True       2023-01-06    50.0
3      U3  2023-01-10    False       2023-01-12   200.0
4      U3  2023-01-10    False       2023-01-20   300.0
5      U3  2023-01-10    False       2023-02-05   400.0
6      U4  2023-01-15     True              NaT     NaN

-----

+++++++++++++++++ left ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id signup_date  churned transaction_date  amount
0      U1  2023-01-01    False       2023-01-03   100.0
1      U1  2023-01-01    False       2023-02-10   500.0
2      U2  2023-01-05     True       2023-01-06    50.0
3      U3  2023-01-10    False       2023-01-12   200.0
4      U3  2023-01-10    False       2023-01-20   300.0
5      U3  2023-01-10    False       2023-02-05   400.0
6      U4  2023-01-15     True              NaT     NaN

-----

+++++++++++++++++ right ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id signup_date  churned transaction_date  amount
0      U1  2023-01-01    False       2023-01-03     100
1      U1  2023-01-01    False       2023-02-10     500
2      U2  2023-01-05     True       2023-01-06      50
3      U3  2023-01-10    False       2023-01-12     200
4      U3  2023-01-10    False       2023-01-20     300
5      U3  2023-01-10    False       2023-02-05     400

-----

In [10]:
transactions_summary = (
    transactions.groupby("user_id")
    .agg(
        total_spend=pd.NamedAgg("amount", "sum"),
        transactions_count=pd.NamedAgg("amount", "count"),
    )
    .reset_index()
)
pr(transactions_summary, "transactions_summary")
user_with_features = users.merge(transactions_summary, on="user_id", how="left")
pr(user_with_features, "user_with_features")
pr(len(users) )
pr(len(user_with_features))

+++++++++++++++++ transactions_summary ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id  total_spend  transactions_count
0      U1          600                   2
1      U2           50                   1
2      U3          900                   3

-----

+++++++++++++++++ user_with_features ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id signup_date  churned  total_spend  transactions_count
0      U1  2023-01-01    False        600.0                 2.0
1      U2  2023-01-05     True         50.0                 1.0
2      U3  2023-01-10    False        900.0                 3.0
3      U4  2023-01-15     True          NaN                 NaN

-----

+++++++++++++++++++++++++++++++++++
<class 'int'>

4

-----

+++++++++++++++++++++++++++++++++++
<class 'int'>

4

-----