In [2]:
from utils import pr
import numpy as np
import pandas as pd

In [5]:
df = pd.DataFrame({
    "user_id": ["001", "002", "003", "004", "005", "006"],
    "age": [25, -3, 40, 200, 30, np.nan],
    "income": [5000, 0, -100, 7000, np.nan, 12000],
    "country": ["US", "US", "FR", "FR", "??", "US"],
    "churned": [False, True, False, False, True, False]
})
pr(df , 'df')
pr(df.describe(include='all') , 'df.describe')
pr(df.dtypes , 'df.dtypes')
pr(df.isna().sum() , 'NA values sum per column')

+++++++++++++++++ df ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id    age   income country  churned
0     001   25.0   5000.0      US    False
1     002   -3.0      0.0      US     True
2     003   40.0   -100.0      FR    False
3     004  200.0   7000.0      FR    False
4     005   30.0      NaN      ??     True
5     006    NaN  12000.0      US    False

-----

+++++++++++++++++ df.describe ++++++++++++++++++
<class 'pandas.DataFrame'>

       user_id         age       income country churned
count        6    5.000000      5.00000       6       6
unique       6         NaN          NaN       3       2
top        001         NaN          NaN      US   False
freq         1         NaN          NaN       3       4
mean       NaN   58.400000   4780.00000     NaN     NaN
std        NaN   80.748375   5093.32897     NaN     NaN
min        NaN   -3.000000   -100.00000     NaN     NaN
25%        NaN   25.000000      0.00000     NaN     NaN
50%        NaN   30.000000   5000.00000     NaN     NaN
75%        NaN   40.000000   7000.00000     NaN     NaN
max        NaN  200.000000  12000.00000     NaN     NaN

-----

+++++++++++++++++ df.dtypes ++++++++++++++++++
<class 'pandas.Series'>

user_id        str
age        float64
income     float64
country        str
churned       bool
dtype: object

-----

+++++++++++++++++ NA values sum per column ++++++++++++++++++
<class 'pandas.Series'>

user_id    0
age        1
income     1
country    0
churned    0
dtype: int64

-----

In [7]:
wrong_df = df[df['age'] > 0]
pr(wrong_df , "Don't do this because it remove meaning")

+++++++++++++++++ Don't do this because it remove meaning ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id    age  income country  churned
0     001   25.0  5000.0      US    False
2     003   40.0  -100.0      FR    False
3     004  200.0  7000.0      FR    False
4     005   30.0     NaN      ??     True

-----

In [8]:
df['invalid_age'] = (df['age'] < 0) | (df['age'] > 120)
pr(df , 'df')

+++++++++++++++++ df ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id    age   income country  churned  invalid_age
0     001   25.0   5000.0      US    False        False
1     002   -3.0      0.0      US     True         True
2     003   40.0   -100.0      FR    False        False
3     004  200.0   7000.0      FR    False         True
4     005   30.0      NaN      ??     True        False
5     006    NaN  12000.0      US    False        False

-----

In [9]:
df['income'].describe()

count        5.00000
mean      4780.00000
std       5093.32897
min       -100.00000
25%          0.00000
50%       5000.00000
75%       7000.00000
max      12000.00000
Name: income, dtype: float64

In [11]:
pr(df['age'].value_counts(dropna=False) , 'value count for the age column')
pr(df['country'].value_counts(dropna=False) , 'Value count for the country column')

+++++++++++++++++ value count for the age column ++++++++++++++++++
<class 'pandas.Series'>

age
 25.0     1
-3.0      1
 40.0     1
 200.0    1
 30.0     1
 NaN      1
Name: count, dtype: int64

-----

+++++++++++++++++ Value count for the country column ++++++++++++++++++
<class 'pandas.Series'>

country
US    3
FR    2
??    1
Name: count, dtype: int64

-----