In [1]:
from utils import pr
from utils import measure_time
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    "user_id": ["U1", "U1", "U2", "U2", "U2", "U3"],
    "transaction_date": pd.to_datetime([
        "2023-01-01", "2023-01-10",
        "2023-01-05", "2023-01-12",
        "2023-02-01", "2023-01-07"
    ]),
    "amount": [100, 200, 50, 75, 300, 500],
    "country": ["US", "US", "US", "US", "US", "FR"]
})

In [7]:
pr(df.groupby('user_id'))
pr(df.groupby('user_id')['amount'])
pr(df.groupby('user_id')['amount'].sum())
pr(df.groupby('user_id')['amount'].sum().reset_index())

+++++++++++++++++++++++++++++++++++
<class 'pandas.api.typing.DataFrameGroupBy'>

-----

+++++++++++++++++++++++++++++++++++
<class 'pandas.api.typing.SeriesGroupBy'>

-----

+++++++++++++++++++++++++++++++++++
<class 'pandas.Series'>

user_id
U1    300
U2    425
U3    500
Name: amount, dtype: int64

-----

+++++++++++++++++++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id  amount
0      U1     300
1      U2     425
2      U3     500

-----

In [10]:
result = df.groupby('user_id')
pr(result)
result = result.agg(
    total_spend=pd.NamedAgg('amount' , 'sum') , 
    mean_spend = pd.NamedAgg('amount' , 'mean') , 
    transactions_count = pd.NamedAgg('amount' , 'count')
)
pr(result)
result = result.reset_index()
pr(result)

+++++++++++++++++++++++++++++++++++
<class 'pandas.api.typing.DataFrameGroupBy'>

-----

+++++++++++++++++++++++++++++++++++
<class 'pandas.DataFrame'>

         total_spend  mean_spend  transactions_count
user_id
U1               300  150.000000                   2
U2               425  141.666667                   3
U3               500  500.000000                   1

-----

+++++++++++++++++++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id  total_spend  mean_spend  transactions_count
0      U1          300  150.000000                   2
1      U2          425  141.666667                   3
2      U3          500  500.000000                   1

-----

In [12]:
df['month'] = df['transaction_date'].dt.to_period('M')
pr(df , 'df')
pr(df.groupby(['user_id' , 'month'])['amount'].sum().reset_index())

+++++++++++++++++ df ++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id transaction_date  amount country    month
0      U1       2023-01-01     100      US  2023-01
1      U1       2023-01-10     200      US  2023-01
2      U2       2023-01-05      50      US  2023-01
3      U2       2023-01-12      75      US  2023-01
4      U2       2023-02-01     300      US  2023-02
5      U3       2023-01-07     500      FR  2023-01

-----

+++++++++++++++++++++++++++++++++++
<class 'pandas.DataFrame'>

  user_id    month  amount
0      U1  2023-01     300
1      U2  2023-01     125
2      U2  2023-02     300
3      U3  2023-01     500

-----